variable "cidr_block" { }
variable "vpc_name" { }
variable "public1_cidr_block" { }
variable "azs" { }
variable "vpc1_name" { }
variable "cidr_block_1" { }
variable "vpc2publicsubnet_cidr_block" { }
variable "azs1" { }
variable "ami" { }
variable "key" { }
variable "instance" { }
variable "pip" { }
variable "ami1" { }
variable "instance_type1" { }
variable "key_name1" { }
variable "pip2" { }